### ISSUE TITLE
selenium headless version & dockerize request

### ISSUE THREAD

**Issue by pasokh** [Brannydonowt/autoinsta#1]
Hi Brannydonowt,
please make selenium headless version & dockerize project for using serverless in docker container & make it on infinite run using sleep time gap between posts.
finest regards

**Comment by Brannydonowt** [comment]
I'll take a look

**Comment by Brannydonowt** [comment]
Hi @pasokh

I've added a headless option in this [commit](https://github.com/Brannydonowt/autoinsta/commit/334e4fef76b208fc9a745247dadd9f88c77b0ea5)

You can pass in True/False for headless mode on line 9 of bot.py
`browser = driver.GetBrowser(headless=True)`

I've moved selenium browser handling to driver.py, so that I can add ease of access features in the future (different browsers, options etc...)

I will get started on Docker soon, I haven't worked with Docker before so can't give an ETA.

**Comment by pasokh** [comment]
Hello again Brannydonowt ,
special thanks for headless commit , 
so interesting to see dockerize commit.
please if it's possible start docker at soonest time you can ..
regards

**Comment by pasokh** [comment]
Im also try to make dockerfile like below , but not work for , you can correct it to save docker learn time:

FROM python:3.9
 
ENV DEBIAN_FRONTEND noninteractive
ENV GECKODRIVER_VER v0.29.0
ENV FIREFOX_VER 87.0
 
RUN set -x \
   && apt update \
   && apt upgrade -y \
   && apt install -y \
       firefox-esr \
   && pip install  \
       requests \
       selenium \
 
# Add latest FireFox
RUN set -x \
   && apt install -y \
       libx11-xcb1 \
       libdbus-glib-1-2 \
   && curl -sSLO https://download-installer.cdn.mozilla.net/pub/firefox/releases/${FIREFOX_VER}/linux-x86_64/en-US/firefox-${FIREFOX_VER}.tar.bz2 \
   && tar -jxf firefox-* \
   && mv firefox /opt/ \
   && chmod 755 /opt/firefox \
   && chmod 755 /opt/firefox/firefox
  
# Add geckodriver
RUN set -x \
   && curl -sSLO https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VER}/geckodriver-${GECKODRIVER_VER}-linux64.tar.gz \
   && tar zxf geckodriver-*.tar.gz \
   && mv geckodriver /usr/bin/
   
   RUN pip install virtualenv
   RUN virtualenv venv
   RUN . /opt/venv/bin/activate && pip install -r requirements.txt
 
COPY ./app /app
 
WORKDIR /app
 
CMD . /opt/venv/bin/activate && exec python bot.py

**Comment by Brannydonowt** [comment]
Integrating Docker support now

**Comment by Brannydonowt** [comment]
I now have a working docker image. I am unable to test that the bot works as expected due to the issue #3 

I'm working on fixing that issue now and will update once I am able to progress further with Docker.

**Comment by Brannydonowt** [comment]
Made some good progress on Dockerizing.

Latest Docker Branch has a buildable image that runs successfully. Working on downloading a trending video at the moment.

**Comment by Brannydonowt** [comment]
Hi @pasokh!

I've successfully uploaded a video via the bot using a docker container. Please build and run a docker image from the latest master using the build command.

`docker build -t autoinsta .`

You HAVE to run in headless mode for it to work. Thanks!
