### ISSUE TITLE
swap msilib with alternative for linux

### ISSUE THREAD

**Issue by bugbounted** [Brannydonowt/autoinsta#2]
Hi [Brannydonowt](https://github.com/Brannydonowt),
please use another package on bot.py line 3 instead of 'from msilib.schema import File' becase msilib is a python module built for the Windows platform, as the [documentation](https://docs.python.org/2/library/msilib.html) shows. Therefore, you should not try and import it in a python script which you run on an Ubuntu platform.
see terminal log in ubuntu 22.04:
`(venv) root@server-virtual-machine:~/autoinsta# python bot.py`
`Traceback (most recent call last):`
`  File "/root/autoinsta/bot.py", line 3, in <module>`
`    from msilib.schema import File`
`ModuleNotFoundError: No module named 'msilib'`
I am waiting for the code to be coordinated for the Linux platform.

**Comment by Brannydonowt** [comment]
I'll jump on this right away

**Comment by Brannydonowt** [comment]
Fixed with commit [62cebef](https://github.com/Brannydonowt/autoinsta/commit/62cebef80ea7c473fff019b351b28ec14a623e73)

Import isn't used. Also tidied up other redundant imports.
